Repository projectpolygon/hypercube, pull requests merged in 2020-05, with the labels that each got.

#18 Base API support
  README.md
  docs/.gitignore
  docs/404.html
  docs/Gemfile
  docs/Gemfile.lock
  docs/_config.yml
  docs/_config.yml.old
  docs/_posts/2020-04-21-welcome-to-jekyll.markdown
  docs/about.markdown
  docs/index.markdown
  src/client/message.py
  src/client/slave.py
  src/common/__init__.py
  src/common/api/example_graphics_task.json
  src/common/api/example_job.json
  src/common/api/new_job.json
  src/common/job.py
  src/common/message.py
  src/common/networking.py
  src/jobfile
  src/master/__init__.py
  src/master/master.py
  src/server/job
  src/server/master.py
  src/server/message.py
  src/slave/__init__.py
  src/slave/slave.py
  src/test/__init__.py
  src/test/test_api.py
Labels: enhancement

#22 Flask Spike Results
  .gitignore
  README.md
  src/common/job.py
  src/common/message.py
  src/jobfile
  src/master/master.py
  src/slave/slave.py
Labels: SPIKE, enhancement

#24 Setting up for the pipeline
  Dockerfile
  README.md
  master.Dockerfile
  slave.Dockerfile
  src/master/requirements.txt
  src/slave/requirements.txt
  src/slave/slave.py
  src/test/test_api.py
  src/tests/__init__.py
  src/tests/common_tests/__init__.py
  src/tests/common_tests/test_networking.py
  src/tests/master_tests/__init__.py
  src/tests/master_tests/test_master.py
  src/tests/requirements.txt
  src/tests/slave_tests/__init__.py
  src/tests/slave_tests/test_slave.py
Labels: enhancement

#26 Pipeline
  .github/workflows/main.yml
  README.md
Labels: enhancement

#28 binary data
  src/master/master.py
  src/slave/slave.py
Labels: enhancement

#37 Fix Tab error
  src/master/master.py
  src/slave/slave.py
Labels: bug
